### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by yinqianzheng** [yinqianzheng/knora#2]
# User Auth
​
## Functionality
​
- [ ] The main button with logo should link to `/feed`
- [ ] Has working demo login
- [ ] Smooth, bug free navigation
​
### Before Login
​
- [ ] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [ ] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [ ] Can't sign up with the same username/email
- [ ] Pressing enter after filling out the session form should use the form data, not the demo user
​
### After Login
​
- [ ] Should not be able to visit `/login` or `/signup`
- [ ] Should be able to refresh the page and still be logged in
​
​
## Style
​
- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
​
## Seeds
- [ ] Adequate and appropriate seeds

**Comment by ronilbhatia** [comment]
Amazing job! This is really great - the functionality is there, styling is on point and you've done a great job doing the temporary notification of the error message at the top of the screen. The only comment I really have is that it took me a bit to notice that error message - maybe make the bar a little taller, and have the text be white & bolded like Quora does it so that it's more noticeable! Apart from that, any other comments I have would be very nitpicky. I'm going to close this issue but would recommend making that one change with the error message rendering - again, great job!
